### PR TITLE
Add spline with update demo

### PR DESCRIPTION
**Pull request by DiegoCardoso**
The demo is lacking some animation due the fact the whole configuration is sent every time a new point is added. A issue was created to address that.

JIRA: CHARTS-627

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/27)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36CCc56W0OaCxzVg6:-Kz36CCc56W0OaCxzVg7:b59pqq5) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L34)):*
> ```Java
>     public static void runWhileAttached(final Component component,
>             final Command task, final int interval, final int initialPause) {
>         // Until reliable push available in our demo servers
> ```

Is this constraint still valid?

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz35xUgkbOXeb0WvP_9:-Kz35xUgkbOXeb0WvP_A:btbepkb) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L47)):*
> ```Java
>                         Thread.sleep(interval);
>                     }
>                 } catch (InterruptedException e) {
> ```

There isn't  much value in catching these exceptions separately. A single catch of `Exception` that logs the exception is enough.

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36THYEOtJLh25aXxK:-Kz36THZlzZCpGjzwVd3:b-qp3iof) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L69)):*
> ```Java
>     }
> 
> }
> ```

Nitpick: want to add a blank line?

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/lineandscatter/SplineUpdatingEachSecond.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36J-JA1xcdVxJ7ci6:-Kz36J-JA1xcdVxJ7ci7:b-jr0s67) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/examples/lineandscatter/SplineUpdatingEachSecond.java#L71)):*
> ```Java
> 	}
> }
> ```

Nitpick: one or two unnecessary blank lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36CCc56W0OaCxzVg6:-Kz3D4qoLP9-bWE70Obl:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L34)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Is this constraint still valid?
</blockquote></details>

Removed.

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz35xUgkbOXeb0WvP_9:-Kz3D7E9Jze07wYmQcGi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L47)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

There isn't  much value in catching these exceptions separately. A single catch of `Exception` that logs the exception is enough.
</blockquote></details>

Done.

---

*[examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36THYEOtJLh25aXxK:-Kz3D_alMVjwGjaiNwvR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/AbstractChartExample.java#L69)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Nitpick: want to add a blank line?
</blockquote></details>

Done.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/lineandscatter/SplineUpdatingEachSecond.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-Kz36J-JA1xcdVxJ7ci6:-Kz3DbF-lcOnuISvBwt0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/309abf7340a1d1254b989ca00412fd1b6686941e/examples/src/main/java/com/vaadin/addon/charts/examples/lineandscatter/SplineUpdatingEachSecond.java#L71)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Nitpick: one or two unnecessary blank lines.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27)*

**Comment by sayo-vaadin** [comment]
Freezes the browser tab if there's a connectivity issue or idling (possibly a Flow bug), but probably good enough.
See https://vaadin.slack.com/archives/C6X43FE8M/p1510907398000197

:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27#-:-Kz8T5-321RE2fWkGqcQ:bx36hvt)*

**Comment by sayo-vaadin** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/27)*

**Pull request merged**
