### PR TITLE
Java models for HighCharts 5 and a basic VaadinChart Flow component

### PR DESCRIPTION
**Pull request by sayo-vaadin**
CHARTS-609 CHARTS-615: 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/1)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 175 files reviewed at latest revision, 1 unresolved discussion.

---

*[integration-test/pom.xml, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KweO1dfRoQB1lDZMV97:-KweO1dfRoQB1lDZMV98:b-6ben3e) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/badbf235e93cfea09bdeb438882e3e47e989e225/integration-test/pom.xml#L164)):*
> ```XML
>                         <containerIncludeJarPattern>^$</containerIncludeJarPattern>
>                         <resourceBases>
>                             <resourceBase>integration-test/src/main/webapp</resourceBase>
> ```

I think if you change `integration-test` to `${project.basedir}` would make it work for the tests and when we run `mvn jetty:run`,  right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by sayo-vaadin** [comment]
*[integration-test/pom.xml, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KweO1dfRoQB1lDZMV97:-KweRYCDEqB6DUvcdt0I:byvyago) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/badbf235e93cfea09bdeb438882e3e47e989e225/integration-test/pom.xml#L164)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

I think if you change `integration-test` to `${project.basedir}` would make it work for the tests and when we run `mvn jetty:run`,  right?
</blockquote></details>

Yes. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 175 files reviewed at latest revision, 3 unresolved discussions.

---

*[pom.xml, line 39 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjhsCG4Vrp2VX6VEtO:-KwjhsCG4Vrp2VX6VEtP:b-1vpvt7) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/pom.xml#L39)):*
> ```XML
>     <scm>
>         <connection>scm:git:https://github.com/vaadin/charts.git</connection>
>         <developerConnection>scm:git:https://github.com/vaadin/charts.git</developerConnection>
> ```

Please, update repo URL

---

*[pom.xml, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjoiN_o3OZ5mWxB6af:-KwjoiN_o3OZ5mWxB6ag:bvne7f0) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/pom.xml#L75)):*
> ```XML
>                 <groupId>com.vaadin</groupId>
>                 <artifactId>vaadin-testbench-core</artifactId>
>                 <version>5.1.0.alpha1</version>
> ```

Here, you are setting TB to 5.1.0.alpha1 and at integration-test`s pom, you are setting 6.0-SNAPSHOT. 

---

*[integration-test/pom.xml, line 28 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjoRhraalJfbF-WBvl:-KwjoRhraalJfbF-WBvm:b-pcz0nk) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/integration-test/pom.xml#L28)):*
> ```XML
>         
>         <servlet.api.version>3.1.0</servlet.api.version>
>         <selenium.server.version>3.4.0</selenium.server.version>
> ```

Is this being used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by sayo-vaadin** [comment]
Review status: 0 of 175 files reviewed at latest revision, 3 unresolved discussions.

---

*[pom.xml, line 39 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjhsCG4Vrp2VX6VEtO:-KwjrkGDfOoSoN96S7v7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/pom.xml#L39)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Please, update repo URL
</blockquote></details>

Done.

---

*[pom.xml, line 75 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjoiN_o3OZ5mWxB6af:-KwjrgaIw-MIlr0yBcVV:b-jm1h98) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/pom.xml#L75)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Here, you are setting TB to 5.1.0.alpha1 and at integration-test`s pom, you are setting 6.0-SNAPSHOT. 
</blockquote></details>

Removed altogether.

---

*[integration-test/pom.xml, line 28 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjoRhraalJfbF-WBvl:-KwjrxJ8TCG5BqzZYLLU:blsdc6x) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/integration-test/pom.xml#L28)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Is this being used?
</blockquote></details>

Yes. See `com.vaadin.addon.charts.ui.Servlet`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 175 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-test/pom.xml, line 28 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwjoRhraalJfbF-WBvl:-KwjuD8MclPNbxsd3TLf:bwcgd1o) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ecc536bfe30a1495b857133e65984b22de23c3d1/integration-test/pom.xml#L28)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Yes. See `com.vaadin.addon.charts.ui.Servlet`
</blockquote></details>

I was referring to the Selenium version property. But I see that you removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by alvarezguille** [comment]
Reviewed 14 of 175 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: 18 of 175 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkQ2E-kkbZ7dk0hysu:-KwkQ2E-kkbZ7dk0hysv:bnmtfl6) (no related file):*
we probably want to use vaadin style guides for non generated code, indentation at least, we can create a task for that

---

*[addon/src/main/frontend/bower.json, line 18 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOQZT6l6UdVqp1jRi:-KwkOQZT6l6UdVqp1jRj:b60oav1) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/bower.json#L18)):*
> git://github.com/vaadin/vaadin-charts#6.0-preview

`#6.0-preview ` should be enough

---

*[addon/src/main/frontend/package.json, line 21 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkPr_63MVaQfwRtlMA:-KwkPr_63MVaQfwRtlMB:buy7pq7) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/package.json#L21)):*
> ```JSON
>   "author": "",
>   "license": "Apache-2.0"
> }
> ```

is this one needed?

---

*[addon/src/main/frontend/polymer.json, line 26 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOaVQ7DfkZC2pf_jY:-KwkOaVQ7DfkZC2pf_jZ:b-6ye70n) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/polymer.json#L26)):*
> ```JSON
>     ]
>   }
> }
> ```

is this file needed at all for the addon?

---

*[integration-test/drivers.xml, line 39 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOpyTXFAFkaQMsKxq:-KwkOpyTXFAFkaQMsKxr:bqrajgy) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/integration-test/drivers.xml#L39)):*
> ```XML
>         </driver>
>     </osx>
> </root>
> ```

do we need this if we use saucelabs?

---

*[integration-test/src/main/frontend/package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkPodkJIw_g1hjRrIe:-KwkPodkJIw_g1hjRrIf:bu98jz6) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/integration-test/src/main/frontend/package.json#L11)):*
>     "bower": "~1.8.0",
should be latest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by sayo-vaadin** [comment]
Review status: 12 of 171 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[addon/src/main/frontend/bower.json, line 18 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOQZT6l6UdVqp1jRi:-KwniFERDsa3HHNnTCiE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/bower.json#L18)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> git://github.com/vaadin/vaadin-charts#6.0-preview

`#6.0-preview ` should be enough
</blockquote></details>

Done.

---

*[integration-test/src/main/frontend/package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkPodkJIw_g1hjRrIe:-KwniH5WceqMyMZO4Ztw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/integration-test/src/main/frontend/package.json#L11)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>     "bower": "~1.8.0",
should be latest
</blockquote></details>

Done.

---

*[addon/src/main/frontend/package.json, line 21 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkPr_63MVaQfwRtlMA:-KwniK9SPJvg_cxSm7mA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/package.json#L21)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this one needed?
</blockquote></details>

Done.

---

*[addon/src/main/frontend/polymer.json, line 26 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOaVQ7DfkZC2pf_jY:-KwniMLIuvncQ9jv1Or9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/addon/src/main/frontend/polymer.json#L26)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this file needed at all for the addon?
</blockquote></details>

Done.

---

*[integration-test/drivers.xml, line 39 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkOpyTXFAFkaQMsKxq:-KwniO-8FAeAbLJCjYCZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/7377b0d838cb7f8e84dbb6ec2c3764c7e414a5a3/integration-test/drivers.xml#L39)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

do we need this if we use saucelabs?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by sayo-vaadin** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1#-KwkQ2E-kkbZ7dk0hysu:-Kwo9YHCHY2z-rRj5rLb:bb71kmx) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

we probably want to use vaadin style guides for non generated code, indentation at least, we can create a task for that
</blockquote></details>

Okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Comment by alvarezguille** [comment]
Reviewed 153 of 175 files at r1, 9 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/1)*

**Pull request merged**
