### PR TITLE
Use latest flow

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159)

### CODE REVIEW

**Comment by alvarezguille** [comment]
needs new component versions with `HasClickListeners` -> `ClickNotifier` change included

**Comment by oluwasayo** [comment]
Reviewed 5 of 6 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159)*

**Comment by alvarezguille** [comment]
*[examples/src/main/java/com/vaadin/flow/component/charts/examples/dynamic/ServerSideEvents.java, line 144 at r2](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159#-LArcTGlE2EkDHFbwQms:-LAruT1d7EhWxPuRLBFy:b-auk0g7) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/cdcbe8fba4ccbcc7e6b97c74dab264b26a241e6a/examples/src/main/java/com/vaadin/flow/component/charts/examples/dynamic/ServerSideEvents.java#L144)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Indentation. `arg0`?
</blockquote></details>

fixed indentation with eclipse and VaadinJavaConventions

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159)*

**Comment by oluwasayo** [comment]
Wait until resolved

---

Reviewed 1 of 3 files at r3.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159#-:-LArzSOB0TGezWIUNM49:byhcda8)*

**Comment by oluwasayo** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/159#-:-LBUpRhX-SbPVfX2qlws:bnfp4nl)*

**Pull request merged**
