### PR TITLE
CHARTS-737: Follow Flow components package naming convention

### PR DESCRIPTION
**Pull request by oluwasayo**
Renamed `com.vaadin.addons.charts` package to `com.vaadin.flow.componen.charts` to be in alignment with the Flow component naming convention.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/103)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Reviewed 576 of 586 files at r1, 1 of 1 files at r2.
Review status: 290 of 295 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3btJuqmWjFUpCMLXID:-L3btJuqmWjFUpCMLXIE:bxnjwnb) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java#L30)):*
> ```Java
> import java.util.List;
> 
> //import com.vaadin.flow.component.charts.ChartOptions;
> ```

Not introduced in this PR, but do you know why this is commented? (Also, I couldn't find this class)

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxTj4lmGUxvaYIcjj:-L3bxTj4lmGUxvaYIcjk:b-pu8xju) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java#L27)):*
> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.examples.dynamic.DynamicChanges;

Duplicated imports

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxZ72SCJ3wHV7fD6b:-L3bxZ72SCJ3wHV7fD6c:b83zvw4) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java#L27)):*
> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.examples.dynamic.DynamicExtremes;

Duplicated imports

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxuUzpL9FBjpqXjQi:-L3bxuUzpL9FBjpqXjQj:b-q4uu4o) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java#L35)):*
> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.Chart;
> import com.vaadin.flow.component.charts.events.ChartClickEvent;
> import com.vaadin.flow.component.charts.events.PointClickEvent;
> import com.vaadin.flow.component.charts.events.PointSelectEvent;
> import com.vaadin.flow.component.charts.events.PointUnselectEvent;
> import com.vaadin.flow.component.charts.events.SeriesCheckboxClickEvent;
> import com.vaadin.flow.component.charts.events.SeriesHideEvent;
> import com.vaadin.flow.component.charts.events.SeriesLegendItemClickEvent;
> import com.vaadin.flow.component.charts.events.SeriesShowEvent;
> import com.vaadin.flow.component.charts.examples.dynamic.ServerSideEvents;
> import com.vaadin.flow.component.charts.model.DataSeries;
> import com.vaadin.flow.component.charts.model.Series;

Duplicated imports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103)*

**Comment by oluwasayo** [comment]
Review status: 288 of 296 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3btJuqmWjFUpCMLXID:-L3bzQUDh3BXi44BHhHb:bms8f2e) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java#L30)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Not introduced in this PR, but do you know why this is commented? (Also, I couldn't find this class)
</blockquote></details>

A couple of classes were moved from Charts 4 but which are no longer referenced. I'd say we remove those in a separate PR.

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxTj4lmGUxvaYIcjj:-L3bzYSudsm5s3E6sDF5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java#L27)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.examples.dynamic.DynamicChanges;

Duplicated imports
</blockquote></details>

Done.

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxZ72SCJ3wHV7fD6b:-L3bzYwMBZr6qVsOsdjI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java#L27)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.examples.dynamic.DynamicExtremes;

Duplicated imports
</blockquote></details>

Done.

---

*[integration-test/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3bxuUzpL9FBjpqXjQi:-L3bzbmhiES8qTB8NoOl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/integration-test/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java#L35)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> import com.vaadin.flow.component.charts.AbstractChartExample;
> import com.vaadin.flow.component.charts.Chart;
> import com.vaadin.flow.component.charts.events.ChartClickEvent;
> import com.vaadin.flow.component.charts.events.PointClickEvent;
> import com.vaadin.flow.component.charts.events.PointSelectEvent;
> import com.vaadin.flow.component.charts.events.PointUnselectEvent;
> import com.vaadin.flow.component.charts.events.SeriesCheckboxClickEvent;
> import com.vaadin.flow.component.charts.events.SeriesHideEvent;
> import com.vaadin.flow.component.charts.events.SeriesLegendItemClickEvent;
> import com.vaadin.flow.component.charts.events.SeriesShowEvent;
> import com.vaadin.flow.component.charts.examples.dynamic.ServerSideEvents;
> import com.vaadin.flow.component.charts.model.DataSeries;
> import com.vaadin.flow.component.charts.model.Series;

Duplicated imports
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103)*

**Comment by DiegoCardoso** [comment]
Reviewed 3 of 586 files at r1, 1 of 6 files at r3.
Review status: 290 of 296 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-L3btJuqmWjFUpCMLXID:-L3c-EgPDM7MBeGlbqei:b-pbdqz3) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0667d71904ed3a2cc22791530c7207480e881655/addon/src/main/java/com/vaadin/flow/component/charts/model/serializers/ChartOptionsBeanSerializerModifier.java#L30)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

A couple of classes were moved from Charts 4 but which are no longer referenced. I'd say we remove those in a separate PR.
</blockquote></details>

Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103)*

**Comment by DiegoCardoso** [comment]
Reviewed 6 of 586 files at r1, 5 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/103#-:-L3c3HNekP8AqwaX1wln:bnfp4nl)*

**Pull request merged**
