### PR TITLE
CHARTS-724: Document breaking changes in Charts 6

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/99)

### CODE REVIEW

**Comment by johannesh2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/charts-breaking-changes-in-version-6.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99#-L3i3SCmF9bwxsSsMMEA:-L3i3SCmF9bwxsSsMMEB:b-rwj8ib) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/576a3e9afa946cfdd5d5b1e8536a9c4489e5904c/documentation/java-api/charts-breaking-changes-in-version-6.asciidoc#L19)):*
> ```AsciiDoc
> * Dropped "size with units" sizing properties in favor of strings to take full advantage of browser capabilities
> * ZAxis is now a subclass of Axis
> * Getting PlotOptionsSeries no longer automatically creates a new instance
> ```

I think it should be mentioned also that Gradients are not supported at all. Same goes for plotBackgroundImage which we don't have  a replacement currently. Is there something else we don't support compared to Charts 4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99)*

**Comment by johannesh2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/charts-breaking-changes-in-version-6.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99#-L3i3SCmF9bwxsSsMMEA:-L3i3tpQN_Y5ABzvMaXF:b-e9bt70) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/576a3e9afa946cfdd5d5b1e8536a9c4489e5904c/documentation/java-api/charts-breaking-changes-in-version-6.asciidoc#L19)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

I think it should be mentioned also that Gradients are not supported at all. Same goes for plotBackgroundImage which we don't have  a replacement currently. Is there something else we don't support compared to Charts 4?
</blockquote></details>

I mean not even in CSS. To me understanding in Charts 6 there is no way to achieve this through Flow API

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99)*

**Comment by oluwasayo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/charts-breaking-changes-in-version-6.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99#-L3i3SCmF9bwxsSsMMEA:-L3i7TextCXNSTjB_mSZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/576a3e9afa946cfdd5d5b1e8536a9c4489e5904c/documentation/java-api/charts-breaking-changes-in-version-6.asciidoc#L19)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

I mean not even in CSS. To me understanding in Charts 6 there is no way to achieve this through Flow API
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99)*

**Comment by johannesh2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/99)*

**Pull request merged**
