### PR TITLE
CHARTS-722: CSS styling documentation

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/79)

### CODE REVIEW

**Comment by johannesh2** [comment]
*[documentation/css/css-styling.asciidoc, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79#-L2dcgWNPE5lSOzBQwOz:-L2dcgWNPE5lSOzBQwP-:b-ispahn) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/68ebaff64f0031d9fd0338a434b8b987b4a563bf/documentation/css/css-styling.asciidoc#L50)):*
> ```AsciiDoc
> [source, java]
> ----
> @HtmlImport("frontend://src/styles/css-style-example.html")
> ```

OK so apparently you need to have this import anyways, but the path could be the shared-styles.html as it's the "best-practice".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79)*

**Comment by johannesh2** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79)*

**Comment by johannesh2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79#-:-L2dgIC5KAeY1abhexH6:bnfp4nl)*

**Comment by oluwasayo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/css/css-styling.asciidoc, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79#-L2dcgWNPE5lSOzBQwOz:-L2diay8SMw-ugMnlsyy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/68ebaff64f0031d9fd0338a434b8b987b4a563bf/documentation/css/css-styling.asciidoc#L50)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

OK so apparently you need to have this import anyways, but the path could be the shared-styles.html as it's the "best-practice".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/79)*

**Pull request merged**
