### PR TITLE
Make master reproducible

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/75)

### CODE REVIEW

**Comment by johannesh2** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/pom.xml, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75#-L2Pd3fdTi2a3Sid8p-k:-L2Pd3feG8fSJ0A_c0Li:b-w7bqtb) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ea958aa7113c061cae7c51259ad00f2fbfc0d0d6/examples/pom.xml#L36)):*
> ```XML
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-radio-button-flow</artifactId>
>             <version>1.0.0.alpha2</version>
> ```

BTW this naturally should be removed as soon as charts is updated to use a platform version with radio-button included

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75)*

**Comment by johannesh2** [comment]
*[examples/pom.xml, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75#-L2Pd3fdTi2a3Sid8p-k:-L2PdKxozPAARqY0sblw:bw276l4) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ea958aa7113c061cae7c51259ad00f2fbfc0d0d6/examples/pom.xml#L36)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

BTW this naturally should be removed as soon as charts is updated to use a platform version with radio-button included
</blockquote></details>

OK I still can't use reviewable the right way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75#-:-L2PeVExDd9gBHPdHgwF:bnfp4nl)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/75)*

**Pull request merged**
