### PR TITLE
CHARTS-694: Demo css snippet

### PR DESCRIPTION
**Pull request by oluwasayo**
- Split demo styles in to multiple theme modules (one per example)
- Scan classpath once and preload all found style modules on page load as `vaadin-themable-mixin` does not readily support live theme reloading
- Empty `shared-styles.html` to only include `vaadin-chart-default-theme` once
- Request handler to serve the static style files and production mode dependency filter to ignore them as they are not bundled
- Documentation update to make Chart users aware that this include should *only* be done in one style module

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/106)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/src/main/webapp/frontend/src/shared-styles.html, line 3 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106#-L4161WpzN2nPnQ4tooX:-L4161WpzN2nPnQ4tooY:b-eclc7m) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ef104bec4c5faa6ba410ba530d95b2953075f438/demo/src/main/webapp/frontend/src/shared-styles.html#L3)):*
> ```HTML
> <dom-module id="shared-styles" theme-for="vaadin-chart">
>   <template>
>     <style include="vaadin-chart-default-theme"></style>
> ```

Shouldn't the default theme be imported here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106)*

**Comment by oluwasayo** [comment]
*[demo/src/main/webapp/frontend/src/shared-styles.html, line 3 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106#-L4161WpzN2nPnQ4tooX:-L416Zm7VY7nWRXRnR-x:bqmlgy6) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ef104bec4c5faa6ba410ba530d95b2953075f438/demo/src/main/webapp/frontend/src/shared-styles.html#L3)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Shouldn't the default theme be imported here?
</blockquote></details>

It's already imported by the `vaadin-chart` element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106)*

**Comment by oluwasayo** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/src/main/webapp/frontend/src/shared-styles.html, line 3 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106#-L4161WpzN2nPnQ4tooX:-L41CFytR4zefedL7Sk3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/ef104bec4c5faa6ba410ba530d95b2953075f438/demo/src/main/webapp/frontend/src/shared-styles.html#L3)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

It's already imported by the `vaadin-chart` element.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106)*

**Comment by DiegoCardoso** [comment]
Reviewed 3 of 16 files at r7, 11 of 13 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/106)*

**Pull request merged**
