### PR TITLE
CHARTS-780: Fix demo in production mode

### PR DESCRIPTION
**Pull request by oluwasayo**
The diff is not so large after #166 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[pom.xml, line 95 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167#-LBuei5D4PLZLs1k8i9V:-LBuei5E2vEbKGJbsQBi:b65a4rl) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/1f7bdbb2582b2c0337dee290bf605526e784b14a/pom.xml#L95)):*
> ```
> PIN webcomponentsjs AS A WORKAROND FOR https://protools.atlassian.net/browse/CHARTS-780
> ```
 
I think it would make more sense to link to the actual issue webjars/1763

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167)*

**Comment by oluwasayo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 95 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167#-LBuei5D4PLZLs1k8i9V:-LBuh1oI4DDnO_QrP9Ov:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/1f7bdbb2582b2c0337dee290bf605526e784b14a/pom.xml#L95)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> ```
> PIN webcomponentsjs AS A WORKAROND FOR https://protools.atlassian.net/browse/CHARTS-780
> ```
 
I think it would make more sense to link to the actual issue webjars/1763
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167)*

**Comment by alvarezguille** [comment]
Reviewed 8 of 8 files at r1, 1 of 2 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/167)*

**Pull request merged**
