### PR TITLE
Demo BoxPlotExample

### PR DESCRIPTION
**Pull request by alexberazouski**
CHARTS-632

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/84)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/BoxPlotExample.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84#-L2u0qO5YzCwDN40ONAQ:-L2u0qO6vMcYT2wPre8_:b-shm0h7) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/8dc2d51094c1c79d1ab98397a14643122188622b/examples/src/main/java/com/vaadin/addon/charts/examples/other/BoxPlotExample.java#L34)):*
> ```Java
>         YAxis yAxis = chart.getConfiguration().getyAxis();
> 
>         yAxis.setTitle("Observations");
> ```

Small thing: I believe you meant to add the empty line after this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84)*

**Comment by alexberazouski** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/BoxPlotExample.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84#-L2u0qO5YzCwDN40ONAQ:-L2uNCASpzJhNGBqNvrF:bnputky) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/8dc2d51094c1c79d1ab98397a14643122188622b/examples/src/main/java/com/vaadin/addon/charts/examples/other/BoxPlotExample.java#L34)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Small thing: I believe you meant to add the empty line after this one.
</blockquote></details>

Done. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84)*

**Comment by oluwasayo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84#-:-L2udjuyFWE0d3q_1uzz:bnfp4nl)*

**Comment by oluwasayo** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/84)*

**Pull request merged**
