### PR TITLE
Remove more style properties

### PR DESCRIPTION
**Pull request by oluwasayo**
Diff is not so large after #95 is merged

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/98)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Please, fix the merge conflicts.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/98#-:-L3Dn1o6SJym_LiBirmt:b-rxfd0u)*

**Comment by oluwasayo** [comment]
Done

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/98#-:-L3Do8NVMr1BHXa-atBf:bb6un1j)*

**Comment by DiegoCardoso** [comment]
Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/98)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/98)*

**Pull request merged**
