### PR TITLE
Add webjar module

### PR DESCRIPTION
**Pull request by johannesh2**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/21)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
I think `webjar/src/main/frontend/bower_components/` should be added `.gitignore`. Also, `demo/pom.xml` module be updated as `integration-test`?

---

Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-test/pom.xml, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzaIy5N4LNr_sku0wb:-KyzaIy5N4LNr_sku0wc:b-emdrmf) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/integration-test/pom.xml#L32)):*
> ```XML
> 
>         
>         <node.version>v8.1.2</node.version>
> ```

Should we use the same node version across all modules? (there's a different node version setting at `webjar/pom.xml`)

---

*[webjar/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzYYl8tgnNyhsmdgJE:-KyzYYl9EvZ9gOMEArVO:bljbvzl) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/webjar/pom.xml#L15)):*
> ```XML
>     <artifactId>vaadin-charts-flow-webjar</artifactId>
>     
> ```

There's no `bower.json` at `addon` and `integration-test` modules.

---

*[webjar/build-tools/yarn.lock, line 0 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzcaBEwol_3o4M_a5L:-KyzcaBEwol_3o4M_a5M:b-wta48i) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/webjar/build-tools/yarn.lock#L0)):*
There's a lot of discussion whether those lock files should be tracked or not. Elements team removed `package-lock.json` (https://github.com/vaadin/vaadin-element-skeleton/pull/74), so should `yarn.lock` also have the same destiny?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-:-KyzeeqQ745K0udpV6Vj:b-jjpg3j)*

**Comment by johannesh2** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-test/pom.xml, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzaIy5N4LNr_sku0wb:-Kz-2BuQKCnbN9Y_oXDX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/integration-test/pom.xml#L32)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Should we use the same node version across all modules? (there's a different node version setting at `webjar/pom.xml`)
</blockquote></details>

Done.

---

*[webjar/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzYYl8tgnNyhsmdgJE:-Kz-0rRwwXN1SH6YXiAx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/webjar/pom.xml#L15)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

There's no `bower.json` at `addon` and `integration-test` modules.
</blockquote></details>

Done.

---

*[webjar/build-tools/yarn.lock, line  at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-KyzcaBEwol_3o4M_a5L:-Kz-0CzTtFo3o8v8tTOx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/webjar/build-tools/yarn.lock#L)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

There's a lot of discussion whether those lock files should be tracked or not. Elements team removed `package-lock.json` (https://github.com/vaadin/vaadin-element-skeleton/pull/74), so should `yarn.lock` also have the same destiny?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Comment by DiegoCardoso** [comment]
Reviewed 7 of 17 files at r1, 1 of 1 files at r5, 2 of 3 files at r7, 3 of 3 files at r9, 1 of 1 files at r10.
Review status: 10 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 17 files at r1, 1 of 1 files at r2.
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/build-tools/package.json, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-Kz2bIKMFlZ7VUOprWZr:-Kz2bIKNDK1Gy-0Qhnyn:b-6oywt9) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/addon/build-tools/package.json#L11)):*
> ```JSON
>   },
>   "scripts": {
>     "install": "cd ../src/main/frontend && bower install"
> ```

I can't find any `bower.json` at `addon/src/main/frontend`. Is this file being used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Comment by johannesh2** [comment]
*[addon/build-tools/package.json, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21#-Kz2bIKMFlZ7VUOprWZr:-Kz2oe9HgzD3GLaVZ97R:b7fop5k) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/13fa937e516529c5f6afbbf5508f03ba264d45d2/addon/build-tools/package.json#L11)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

I can't find any `bower.json` at `addon/src/main/frontend`. Is this file being used?
</blockquote></details>

That's accidentally added. Thank you for noticing. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 1 files at r3, 1 of 2 files at r11.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/21)*

**Pull request merged**
