### PR TITLE
Add Area Spline demo

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Add Area Spline demo as seen in FW8 demo

JIRA: CHARTS-625

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/24)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24#-Kyuz6_SdGAp4v9astLw:-Kyuz6_SdGAp4v9astLx:bjw1pxq) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/152ec9b53183c342c3490941bb50b62f538d9abc/.gitignore#L14)):*
> **/frontend/node_modules
> **/frontend/node

still needed? for which module?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24)*

**Comment by DiegoCardoso** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24#-Kyuz6_SdGAp4v9astLw:-KyvRp_2jeZbcDztI_EX:b-y0976u) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/152ec9b53183c342c3490941bb50b62f538d9abc/.gitignore#L14)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> **/frontend/node_modules
> **/frontend/node

still needed? for which module?
</blockquote></details>

Changed it, so it's more specific. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24)*

**Comment by sayo-vaadin** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24)*

**Comment by sayo-vaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/24#-:-KyzaXy_xb5S4oyuIRjF:bnfp4nl)*

**Pull request merged**
