### PR TITLE
Fix demo app for small screens

### PR DESCRIPTION
**Pull request by DiegoCardoso**
- Add support for small screens
- Remove viewport selection on small screens
- Add theme color

JIRA: CHARTS-676

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/110)

### CODE REVIEW

**Comment by oluwasayo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/src/main/java/com/vaadin/flow/component/charts/ApplicationServiceInitListener.java, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110#-L45MsTjbp59y3l0p3cK:-L45MsTjbp59y3l0p3cL:bwiid9z) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/14088485ecb876e7e0191408acb01e5cf6ba0c72/demo/src/main/java/com/vaadin/flow/component/charts/ApplicationServiceInitListener.java#L14)):*
> ```Java
>     @Override
>     public void serviceInit(ServiceInitEvent event) {
>         event.addBootstrapListener(new CustomBootstrapListener());
> ```

BootstrapListener is a SAM type so can be replaced with a lambda (removing the need for a new class).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/src/main/java/com/vaadin/flow/component/charts/ApplicationServiceInitListener.java, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110#-L45MsTjbp59y3l0p3cK:-L46TijreLZV-ZAwTXRd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/14088485ecb876e7e0191408acb01e5cf6ba0c72/demo/src/main/java/com/vaadin/flow/component/charts/ApplicationServiceInitListener.java#L14)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

BootstrapListener is a SAM type so can be replaced with a lambda (removing the need for a new class).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110)*

**Comment by oluwasayo** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110)*

**Comment by oluwasayo** [comment]
Reviewed 1 of 3 files at r3.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110)*

**Comment by oluwasayo** [comment]
Reviewed 2 of 5 files at r1, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/110)*

**Pull request merged**
