### PR TITLE
Upgrade to Flow Beta12 and be serializable

### PR DESCRIPTION
**Pull request by oluwasayo**
- Upgrade to Flow Beta12
- Make classes serializable

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[addon/pom.xml, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMt43_A580IkC9F3Dh:-LDMt43a6k0gCqj04wMn:b-wuzil) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/pom.xml#L41)):*
> ```XML
>             <groupId>com.vaadin</groupId>
>             <artifactId>flow-test-generic</artifactId>
>             <version>1.0.0.beta12</version>
> ```

Why not beta12? why todo is removed? better to have the variable here

---

*[addon/src/main/java/com/vaadin/flow/component/charts/Chart.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMtM_u0IuqxhxfJBOp:-LDMtM_u0IuqxhxfJBOq:bu75g3s) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/Chart.java#L76)):*
> ```Java
>     private Configuration configuration;
> 
>     transient JreJsonFactory jsonFactory = new JreJsonFactory();
> ```

why not private?
why not static?

---

*[addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java, line 47 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMu1GkAjZGDwGPrw4w:-LDMu1GkAjZGDwGPrw4x:b6q192f) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java#L47)):*
> ```Java
>             chart.getElement().callFunction("__callSeriesFunction",
>                     "addPoint", getSeriesIndex(event),
>                     chart.jsonFactory.parse(
> ```

Object encapsulation is broken everywhere here

---

*[addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMuSLDDE6pD6-FQnpw:-LDMuSLDDE6pD6-FQnpx:b-g9gqgx) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java#L29)):*
> ```Java
>     public void verifyJsonFactoryDeserialization() {
>         final Chart chart = new Chart();
>         final ByteArrayOutputStream objectOutStore = new ByteArrayOutputStream();
> ```

You can use `super.serializeAndDeserialize(T)` here 
#DRY, #FFS

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)*

**Comment by oluwasayo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/pom.xml, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMt43_A580IkC9F3Dh:-LDMwfOJ8wywtBw6yjwB:bk4v9jt) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/pom.xml#L41)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why not beta12? why todo is removed? better to have the variable here
</blockquote></details>

Yes that would be the ideal thing to do but we can't use beta12 yet because of an issue. We'll change this on the next Flow release. 

---

*[addon/src/main/java/com/vaadin/flow/component/charts/Chart.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMtM_u0IuqxhxfJBOp:-LDN0g9EAvPkC0kvj81g:b-9i9abm) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/Chart.java#L76)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

why not private?
why not static?
</blockquote></details>

Not static because I'm not sure if JreJsonFactory is threadsafe. Couldn't find anything doc about its thread safety.
Consequently not private because I wanted to keep the current behavior of the class after deserialization (i.e a shared instance with the enclosing chart) 

---

*[addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java, line 47 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMu1GkAjZGDwGPrw4w:-LDN1QbtCZziA_g1h-le:b-wyozf6) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java#L47)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Object encapsulation is broken everywhere here
</blockquote></details>

It's package private. But you're right, it could be private but with a package private getter and the getter could even remove the need for the readResolve. 

---

*[addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMuSLDDE6pD6-FQnpw:-LDN1KhPBHYQ0dKUlz90:b-tqs5gq) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java#L29)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

You can use `super.serializeAndDeserialize(T)` here 
#DRY, #FFS
</blockquote></details>

I want aware of this method. I'll update. Thanks. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)*

**Comment by oluwasayo** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/pom.xml, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMt43_A580IkC9F3Dh:-LD_yb30DLSTlSonSjiC:b-ur7sn1) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/pom.xml#L41)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Yes that would be the ideal thing to do but we can't use beta12 yet because of an issue. We'll change this on the next Flow release. 
</blockquote></details>

TODO restored.

---

*[addon/src/main/java/com/vaadin/flow/component/charts/Chart.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMtM_u0IuqxhxfJBOp:-LD_yhlr1y5fqLhGQFcy:bc8fmqb) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/Chart.java#L76)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Not static because I'm not sure if JreJsonFactory is threadsafe. Couldn't find anything doc about its thread safety.
Consequently not private because I wanted to keep the current behavior of the class after deserialization (i.e a shared instance with the enclosing chart) 
</blockquote></details>

Now private. Not static because `JreJsonFactory` might not be threadsafe.
https://github.com/tbroyer/gwt-sandbox/blob/master/elemental/src/elemental/json/impl/JreJsonFactory.java#L64

---

*[addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java, line 47 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMu1GkAjZGDwGPrw4w:-LD_zBsY5cw4ANYCQgCm:b-d430av) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java#L47)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

It's package private. But you're right, it could be private but with a package private getter and the getter could even remove the need for the readResolve. 
</blockquote></details>

Strengthened a bit with a package-visible getter.

---

*[addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMuSLDDE6pD6-FQnpw:-LD_zKeA1CJo1Cn18ADR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/test/java/com/vaadin/flow/component/charts/ChartsSerializableTest.java#L29)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

I want aware of this method. I'll update. Thanks. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)*

**Comment by DiegoCardoso** [comment]
:lgtm:

@elmot do you agree with latest changes?

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-:-LDaeyO68MTdrBv_52i6:b-6g1dvj)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[addon/src/main/java/com/vaadin/flow/component/charts/Chart.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMtM_u0IuqxhxfJBOp:-LDb0V9g0E0okDcnkJFw:b7zpn7m) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/Chart.java#L76)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Now private. Not static because `JreJsonFactory` might not be threadsafe.
https://github.com/tbroyer/gwt-sandbox/blob/master/elemental/src/elemental/json/impl/JreJsonFactory.java#L64
</blockquote></details>

The code shown looks thread-safe, but ok, let's keep it as is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-:-LDb1ObC0eCVP26LUyGd:bnfp4nl)*

**Comment by oluwasayo** [comment]
*[addon/src/main/java/com/vaadin/flow/component/charts/Chart.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180#-LDMtM_u0IuqxhxfJBOp:-LDbYSy9BnNezQsaYHVr:b-xd3vm6) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fa5cac34258fed0f5ad2c5cc55954151ed613dfe/addon/src/main/java/com/vaadin/flow/component/charts/Chart.java#L76)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The code shown looks thread-safe, but ok, let's keep it as is.
</blockquote></details>

You're right.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/180)*

**Pull request merged**
