### PR TITLE
Add installing section for docs

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/62)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/charts-installing.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62#-L0KD4JW4gGpWkVhOxZP:-L0KD4JW4gGpWkVhOxZQ:b-8f8wnv) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/1a7cabe4ed3ab432f5da291bef72cc003706458d/documentation/java-api/charts-installing.asciidoc#L22)):*
> [subs="normal"]
> ----
> &lt;dependency&gt;
>     &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
>     &lt;artifactId&gt;vaadin-charts-flow&lt;/artifactId&gt;
>     &lt;version&gt;[replaceable]##6.0.0.alpha6##&lt;/version&gt;
> &lt;/dependency&gt;
> ----

Why this code snippet is different from the following one (`&lt;` instead of `<`and the [] prefixing, for instance)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62)*

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/java-api/charts-installing.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62#-L0KD4JW4gGpWkVhOxZP:-L0KmOLnPFAHu2dygbV6:b2q7bht) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/1a7cabe4ed3ab432f5da291bef72cc003706458d/documentation/java-api/charts-installing.asciidoc#L22)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> [subs="normal"]
> ----
> &lt;dependency&gt;
>     &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
>     &lt;artifactId&gt;vaadin-charts-flow&lt;/artifactId&gt;
>     &lt;version&gt;[replaceable]##6.0.0.alpha6##&lt;/version&gt;
> &lt;/dependency&gt;
> ----

Why this code snippet is different from the following one (`&lt;` instead of `<`and the [] prefixing, for instance)?
</blockquote></details>

BTW. do we still need to use those MarkoG custom styles. I don't think that replaceable class is used anywhere in vaadin docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62)*

**Comment by alvarezguille** [comment]
*[documentation/java-api/charts-installing.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62#-L0KD4JW4gGpWkVhOxZP:-L0LEJcJhkkW3g2qTxKb:b-3f6lya) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/1a7cabe4ed3ab432f5da291bef72cc003706458d/documentation/java-api/charts-installing.asciidoc#L22)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

BTW. do we still need to use those MarkoG custom styles. I don't think that replaceable class is used anywhere in vaadin docs.
</blockquote></details>

Good point, I got snippets from different docs and they were different. 
Now unified style and FFS no more replaceable and it's all as xml source

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62)*

**Comment by johannesh2** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/62)*

**Pull request merged**
