### PR TITLE
Event support

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/67)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/src/main/java/com/vaadin/addon/charts/ClickEvent.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67#-L0iyFjkVDGu2rj_6R4w:-L0iyFjkVDGu2rj_6R4x:b-irnu98) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/c73a33bb7479b08ab913c58137e541292708e3ea/addon/src/main/java/com/vaadin/addon/charts/ClickEvent.java#L13)):*
> ····

spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by oluwasayo** [comment]
*[addon/src/main/java/com/vaadin/addon/charts/ClickEvent.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67#-L0iyFjkVDGu2rj_6R4w:-L0j35prW8OzemewQgus:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/c73a33bb7479b08ab913c58137e541292708e3ea/addon/src/main/java/com/vaadin/addon/charts/ClickEvent.java#L13)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> ····

spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 273 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67#-L0j6tLF7EicSXqOUG0n:-L0j6tLF7EicSXqOUG0o:be2r7ga) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/c73a33bb7479b08ab913c58137e541292708e3ea/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L273)):*
> ```Java
>     public Registration addLegendItemClickListener(
>             ComponentEventListener<SeriesLegendItemClickEvent> listener) {
>         //setSeriesVisibilityTogglingDisabled(true);
> ```

delete this and update javadoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by oluwasayo** [comment]
*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 273 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67#-L0j6tLF7EicSXqOUG0n:-L0jE-QtldaVQicmXEC6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/c73a33bb7479b08ab913c58137e541292708e3ea/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L273)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

delete this and update javadoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67)*

**Comment by alvarezguille** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/67#-:-L0jEM3_ghH8BNe1FFes:bnfp4nl)*

**Pull request merged**
