### PR TITLE
Remove redundant type arguments

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/37)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Similar comment applies here as in #39 , sources under `model/src...` are generated and shouldn't be modified directly in the repo. 

We could accept the changes for the other sources. And I will try to figure out the redundant type arguments in generated code, can't do that immediately though.

If you want you can only include changes for non `model` modules it will be very much welcomed, thanks!

**Comment by asashour** [comment]
Done, thanks.

**Comment by alvarezguille** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/37)*

**Comment by alvarezguille** [comment]
That was fast, thanks!

**Pull request merged**
