### PR TITLE
Column and pie (introducing CSS styling)

### PR DESCRIPTION
**Pull request by sayo-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/29)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
As we can't do much styling with the our API, should we remove all code related to that?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/29#-:-KzNgcEhgS1Ie_CgvHtb:b-c4oma6)*

**Comment by sayo-vaadin** [comment]
Yes, there will be a ticket for that in the generator project. Probably a separate PR to remove the style configurations from the current demos too.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/29#-:-KzNk2yIGqX8lvBMbHQK:b-lpfhkt)*

**Comment by DiegoCardoso** [comment]
Can the style configuration be removed right away for this demo?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/29#-:-KzNlDaK2tgyQasFKlzS:b-rtg1vl)*

**Comment by sayo-vaadin** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/29#-:-KzNnZjt4J7pD_OvMti6:b-896fix)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/29#-:-KzONMI2HFE_gdguL-RN:bnfp4nl)*

**Pull request merged**
