### PR TITLE
CHARTS-693: Remove style config

### PR DESCRIPTION
**Pull request by sayo-vaadin**
Removed unused Java style properties in favor of CSS styling.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/56)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 53 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[model/src/main/java/com/vaadin/addon/charts/model/Legend.java, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56#-L-Xq5r7PUx3jRTOOD-x:-L-Xq5r8csq0xoUfu5W6:b-xg9nmt) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/546a42b12bcc90c7e73bef9d54ccde3e517e82c4/model/src/main/java/com/vaadin/addon/charts/model/Legend.java#L14)):*
> private Number borderRadius;

quick test showed that this doesn't work in styled mode either

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56)*

**Comment by alvarezguille** [comment]
Reviewed 52 of 53 files at r1, 1 of 1 files at r2.
Review status: 52 of 53 files reviewed at latest revision, 1 unresolved discussion.

---

*[model/src/main/java/com/vaadin/addon/charts/model/Handles.java, line 16 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56#-L-a0nhvTBX5C7_zakAS:-L-a0nhvTBX5C7_zakAT:bw6tjz3) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/d2157f89211093003a188ad9d5de02dc877364fe/model/src/main/java/com/vaadin/addon/charts/model/Handles.java#L16)):*
> public class Handles extends AbstractConfigurationObject {

should we skip this class generation?

---

*[model/src/main/java/com/vaadin/addon/charts/model/Legend.java, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56#-L-Xq5r7PUx3jRTOOD-x:-L-a0sCFXG6dGCkyAFRY:b-na8l62) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/546a42b12bcc90c7e73bef9d54ccde3e517e82c4/model/src/main/java/com/vaadin/addon/charts/model/Legend.java#L14)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> private Number borderRadius;

quick test showed that this doesn't work in styled mode either
</blockquote></details>

my bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56)*

**Comment by sayo-vaadin** [comment]
Review status: 52 of 53 files reviewed at latest revision, 1 unresolved discussion.

---

*[model/src/main/java/com/vaadin/addon/charts/model/Handles.java, line 16 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56#-L-a0nhvTBX5C7_zakAS:-L-aUJUBToVvOMu6R1rx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/d2157f89211093003a188ad9d5de02dc877364fe/model/src/main/java/com/vaadin/addon/charts/model/Handles.java#L16)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> public class Handles extends AbstractConfigurationObject {

should we skip this class generation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/56)*

**Pull request merged**
