### PR TITLE
CHARTS-721: Timeline documentation

### PR DESCRIPTION
**Pull request by oluwasayo**
We don't have this demo yet: https://demo.vaadin.com/charts/#CompareMultipleSeries
Tracked by https://protools.atlassian.net/browse/CHARTS-730

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/80)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/java-api/charts-timeline.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80#-L2dcw7Q1R47GzrTFyCG:-L2dcw7Q1R47GzrTFyCH:b2m47rc) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/dd9d6272f9fdbfe03dadbdddb8e271c81b1533bc/documentation/java-api/charts-timeline.asciidoc#L23)):*
> Enabling the timeline in these chart types will raise a runtime exception.

I don't think this is accurate. Charts 4 has a private method `validateTimelineAndConfiguration` which tests if timeline is set to any of the listed types. I guess we should add a task for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by oluwasayo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/java-api/charts-timeline.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80#-L2dcw7Q1R47GzrTFyCG:-L2dj5FqRMmy_1FENxnm:b-pdicdd) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/dd9d6272f9fdbfe03dadbdddb8e271c81b1533bc/documentation/java-api/charts-timeline.asciidoc#L23)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> Enabling the timeline in these chart types will raise a runtime exception.

I don't think this is accurate. Charts 4 has a private method `validateTimelineAndConfiguration` which tests if timeline is set to any of the listed types. I guess we should add a task for that.
</blockquote></details>

If we know all timeline chart types, perhaps we should make the component determine the timeline config by itself without requiring the developer to explicitly set it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/java-api/charts-timeline.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80#-L2dcw7Q1R47GzrTFyCG:-L2djYD2uqp5bWYH30qM:b85skhu) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/dd9d6272f9fdbfe03dadbdddb8e271c81b1533bc/documentation/java-api/charts-timeline.asciidoc#L23)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

If we know all timeline chart types, perhaps we should make the component determine the timeline config by itself without requiring the developer to explicitly set it.
</blockquote></details>

The thing is that Highcharts and Highstock share a list of chart types. What Charts 4 does is to test against this list of unsupported types if timeline is true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by johannesh2** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by johannesh2** [comment]
Reviewed 2 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by johannesh2** [comment]
Reviewed 1 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80#-:-L2uU5zDAQbFAR3Kq2kC:bnfp4nl)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/80)*

**Pull request merged**
