### PR TITLE
Demo Gauge chart with Dual Axes

### PR DESCRIPTION
**Pull request by alexberazouski**
CHARTS-630

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/82)

### CODE REVIEW

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2aEh4dJQ8LcP6HTAc-:-L2aEh4dJQ8LcP6HTAc0:b-cz92mr) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/4a3c076efbbde78abff1f1525cf78a3e467be9eb/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L29)):*
> ```Java
>         configuration.getChart().setType(ChartType.GAUGE);
>         configuration.getChart().setAlignTicks(false);
>         configuration.getChart().setPlotBackgroundColor(null);
> ```

I would suspect that setting plotBackgroundColor(), setPlotBackgroundImage(), setPlotBorderWidth don't affect the demo at all.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2aFHzve3LoEh1yY062:-L2aFHzve3LoEh1yY063:bc9w78) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/4a3c076efbbde78abff1f1525cf78a3e467be9eb/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L42)):*
> ```Java
>         yAxis.setMin(0);
>         yAxis.setMax(200);
>         yAxis.setLineColor(new SolidColor("#339"));
> ```

yAxis and yAxis2 set*Color() don't probably work at all. Please re-test without these settings to reduce the code needed for the sample.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82)*

**Comment by alexberazouski** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2aEh4dJQ8LcP6HTAc-:-L2atK_mjm7KrGHWSqYz:b-gz5iw7) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/d0f9798c84cfc08083872a821aeb54043691db23/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L29)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

I would suspect that setting plotBackgroundColor(), setPlotBackgroundImage(), setPlotBorderWidth don't affect the demo at all.
</blockquote></details>

Removed. And I didn't notice any changes in chart display. 

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2aFHzve3LoEh1yY062:-L2atIBASh6zHPjkxgqy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/d0f9798c84cfc08083872a821aeb54043691db23/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L42)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

yAxis and yAxis2 set*Color() don't probably work at all. Please re-test without these settings to reduce the code needed for the sample.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82)*

**Comment by oluwasayo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2diEJgv12fR21EnPtQ:-L2diEJgv12fR21EnPtR:b36m4wi) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L24)):*
> ```Java
>         final Random random = new Random(0);
>         final Chart chart = new Chart();
>         chart.getElement().getStyle().set("width", "500px");
> ```

If the size is really needed, consider replacing with `chart.getConfiguration().getChart().setWidth(500)`

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2dhdZMIkVX5ynmGcQT:-L2dhdZMIkVX5ynmGcQU:badjbc1) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L74)):*
> ```Java
>                 .getDataLabels()
>                 .setFormatter(
>                         "function() {return '<span style=\"color:#339\">'+ this.y + ' km/h</span><br/>' + '<span style=\"color:#933\">' + Math.round(this.y * 0.621) + ' mph</span>';}");
> ```

Consider replacing color style with standard highchart class names (e.g `highcharts-color-0` and `highcharts-color-1`)

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2dhqPMyAQBvUJwyaeZ:-L2dhqPMyAQBvUJwyae_:b-67p797) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L91)):*
> ```Java
>         add(chart);
>     }
> }
> ```

Nickpick: a trailing blank line would be nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82)*

**Comment by alexberazouski** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2diEJgv12fR21EnPtQ:-L2dnSEDFxI4_Vxd2RFr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L24)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

If the size is really needed, consider replacing with `chart.getConfiguration().getChart().setWidth(500)`
</blockquote></details>

Done.

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2dhdZMIkVX5ynmGcQT:-L2dmZVuJbYYFS0czp_j:bbiq1tt) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L74)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Consider replacing color style with standard highchart class names (e.g `highcharts-color-0` and `highcharts-color-1`)
</blockquote></details>

Done. Using custom style names 

---

*[examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-L2dhqPMyAQBvUJwyaeZ:-L2dn1HA_KXjatUokTPq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/77423b28acb3140d2e29378b45606dfe29c9a633/examples/src/main/java/com/vaadin/addon/charts/examples/other/GaugeWithDualAxes.java#L91)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Nickpick: a trailing blank line would be nice
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82)*

**Comment by sayo-vaadin** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-:-L2eSmq4GDPy0C43PVSl:bnfp4nl)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82#-:-L2eW8OAuDas7Ye7Djm0:bnfp4nl)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/82)*

**Pull request merged**
