### PR TITLE
Remove generated color usages

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/125)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 3 of 4 files at r6.
Review status: 3 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts-flow/125)*

**Comment by oluwasayo** [comment]
Reviewed 44 of 44 files at r1.
Review status: 43 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/125)*

**Comment by oluwasayo** [comment]
Reviewed 5 of 6 files at r2.
Review status: 48 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/src/main/java/com/vaadin/flow/component/charts/examples/area/AreaSpline.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/125#-L4udPWD8UAT_vrdAH-d:-L4udPWEpCLWILzJZ2k6:bdny5zh) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/76fec10d933d8bb3328ae31524d79344e419d75c/examples/src/main/java/com/vaadin/flow/component/charts/examples/area/AreaSpline.java#L45)):*
> ```Java
> 		xAxis.setCategories(new String[] { "Monday", "Tuesday", "Wednesday",
> 				"Thursday", "Friday", "Saturday", "Sunday" });
> 		// add blue background for the weekend
> ```

Is this comment still valid?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/125)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 44 files at r1.
Review status: 48 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/src/main/java/com/vaadin/flow/component/charts/examples/area/AreaSpline.java, line 45 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts-flow/125#-L4udPWD8UAT_vrdAH-d:-L4uek2PChuVYirlsSX7:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/76fec10d933d8bb3328ae31524d79344e419d75c/examples/src/main/java/com/vaadin/flow/component/charts/examples/area/AreaSpline.java#L45)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Is this comment still valid?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts-flow/125)*

**Comment by oluwasayo** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r4, 3 of 4 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/125)*

**Pull request merged**
