### PR TITLE
Add Java API 

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Add Java API as seen at Vaadin Charts for FW. Most of the configurations are taken from there, with some adjustments. 
Use JSON API from Vaadin Charts element to pass data from server to client.
Add some tests.

JIRA: CHARTS-592

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/8)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
I assume the classes in `addon/.../model*` have not undergone any significant changes from what they used to be in the FW version

---

Review status: 0 of 52 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMnXSejiDzfO4C-jWu:-KxMnXSejiDzfO4C-jWv:bfn0wlq) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java#L46)):*
> ```Java
> 		final UI ui = attachEvent.getUI();
> 
> 	 	ui.beforeClientResponse(this, () -> {
> ```

Nitpick: indentation

---

*[addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMndv_4GEWyWOIYHVg:-KxMndvanZSlVKmT9wTP:bm8qltn) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java#L73)):*
> ```Java
> 		Configuration configuration = getConfiguration();
> 
> 		final JreJsonFactory jsonFactory = new JreJsonFactory();
> ```

This can be a class constant

---

*[integration-test/src/main/java/com/vaadin/addon/charts/ui/MainView.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMn6DN2R1kR7JL9F5s:-KxMn6DOOxcJzZjBQUAa:bof01wa) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/integration-test/src/main/java/com/vaadin/addon/charts/ui/MainView.java#L19)):*
> ```Java
> 
> import com.vaadin.addon.charts.VaadinChart;
> import com.vaadin.addon.charts.model.*;
> ```

Do we have a team policy regarding wildcard imports?

---

*[integration-test/src/test/java/com/vaadin/addon/charts/ui/VaadinChartIT.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMmxFr8oQljUqXmoJZ:-KxMmxFsLQ_mtXr7acpv:b574smb) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/integration-test/src/test/java/com/vaadin/addon/charts/ui/VaadinChartIT.java#L42)):*
> ```Java
> 	}
> 
> 	@After
> ```

This does nothing

---

*[model/src/main/java/com/vaadin/addon/charts/model/ZAxis.java, line 530 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMmVopOfZfvkJLu4E1:-KxMmVopOfZfvkJLu4E2:bptw0xl) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0409dca96e38068a36d74c28498bab5c4bcef0b9/model/src/main/java/com/vaadin/addon/charts/model/ZAxis.java#L530)):*
> ```Java
> 	 * the <code>max</code> value might be rounded up.
> 	 * </p>
> 	 * 
> ```

We should avoid changing model classes. The generator project should be the source of truth for model classes. Perhaps we should fix generator to not generate the whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-:-KxMoAgxcqIjB_NwRA1k:bt330np)*

**Comment by alvarezguille** [comment]
about `addon/.../model` I'll create a separate ticket as this might have some issues with OSGI support

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-:-KxN5fG2XhSnmiazYFwd:bwefztv)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 51 files reviewed at latest revision, 5 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMnXSejiDzfO4C-jWu:-KxN6DiLVW7ET0l2OCoQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java#L46)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Nitpick: indentation
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMndv_4GEWyWOIYHVg:-KxN6EI_5bkc_mp0yD-a:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/addon/src/main/java/com/vaadin/addon/charts/VaadinChart.java#L73)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

This can be a class constant
</blockquote></details>

Done.

---

*[integration-test/src/main/java/com/vaadin/addon/charts/ui/MainView.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMn6DN2R1kR7JL9F5s:-KxN6F7ItrLhtg06f4yq:bo8mjmo) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/integration-test/src/main/java/com/vaadin/addon/charts/ui/MainView.java#L19)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Do we have a team policy regarding wildcard imports?
</blockquote></details>

Removed the wildcard.

---

*[integration-test/src/test/java/com/vaadin/addon/charts/ui/VaadinChartIT.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMmxFr8oQljUqXmoJZ:-KxN6HcUUFIazcl-bZC_:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/64dc3b31618885a74dd17490bebebd09a9d15629/integration-test/src/test/java/com/vaadin/addon/charts/ui/VaadinChartIT.java#L42)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

This does nothing
</blockquote></details>

Removed.

---

*[model/src/main/java/com/vaadin/addon/charts/model/ZAxis.java, line 530 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxMmVopOfZfvkJLu4E1:-KxN65RDAAHFBET3Q8Fp:bbp61xx) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/0409dca96e38068a36d74c28498bab5c4bcef0b9/model/src/main/java/com/vaadin/addon/charts/model/ZAxis.java#L530)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

We should avoid changing model classes. The generator project should be the source of truth for model classes. Perhaps we should fix generator to not generate the whitespace.
</blockquote></details>

This was made by mistake while I was trying to fix some stuff with the JSON generation,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8)*

**Comment by alvarezguille** [comment]
Review status: 0 of 51 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8#-KxN5y9je5XpG0LYULbP:-KxN5y9je5XpG0LYULbQ:brb2y86) (no related file):*
the changes look good, I personally would like to avoid
```
final JreJsonFactory jsonFactory = new JreJsonFactory();
final JsonObject configurationNode = jsonFactory.parse(ChartSerialization.toJSON(configuration));
```
if possible, as we're creating the string to then create the JSON object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8)*

**Comment by johannesh2** [comment]
Reviewed 48 of 52 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/8)*

**Pull request merged**
