### PR TITLE
Timeline chart validation

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/92)

### CODE REVIEW

**Comment by johannesh2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92#-L37T5SKixI2gGwzpfVT:-L37T5SLJJhAewSoSmwg:b-fd6opo) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/bdd5595295525433d55ebbd288dab956b8ab34de/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L118)):*
> ```Java
>      *            true for timeline chart
>      */
>     public void setTimeline(Boolean timeline) {
> ```

Add Javadoc for setTimeline to indicate that setTimeline should not be called for these unsupported chart types.

---

*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92#-L37RzPuLzf46YIoCxLJ:-L37RzPuLzf46YIoCxLK:bmourb2) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/bdd5595295525433d55ebbd288dab956b8ab34de/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L126)):*
> ```Java
>             final ChartType type = getConfiguration().getChart().getType();
>             if (TIMELINE_NOT_SUPPORTED.contains(type)) {
>                 throw new RuntimeException(
> ```

Use IAE instead of RuntimeException to indicate that caller has passed a wrong argument. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92)*

**Comment by oluwasayo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92#-L37T5SKixI2gGwzpfVT:-L37YwXPWsY1v0izS9TU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/bdd5595295525433d55ebbd288dab956b8ab34de/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L118)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

Add Javadoc for setTimeline to indicate that setTimeline should not be called for these unsupported chart types.
</blockquote></details>

Done.

---

*[addon/src/main/java/com/vaadin/addon/charts/Chart.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92#-L37RzPuLzf46YIoCxLJ:-L37YxvBK1ZpMYLO1gSZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/bdd5595295525433d55ebbd288dab956b8ab34de/addon/src/main/java/com/vaadin/addon/charts/Chart.java#L126)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

Use IAE instead of RuntimeException to indicate that caller has passed a wrong argument. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92)*

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/java-api/charts-timeline.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92#-L37srPv5ZkWuwY8m61c:-L37srPv5ZkWuwY8m61d:b-717zgo) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/c979637f01e856f8fc0f07c37aca7f9e59456167/documentation/java-api/charts-timeline.asciidoc#L23)):*
> ```AsciiDoc
> <<charts-charttypes#charts.charttypes.funnel, `pyramid`>>, and
> <<charts-charttypes#charts.charttypes.funnel, `funnel`>>.
> Enabling the timeline in these chart types will raise an `IllegalArgumentException`.
> ```

I think this mention about IAE should be in javadoc. And the more generic "Timeline is not supported for these chart types" etc should be here in docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92)*

**Comment by johannesh2** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/92)*

**Pull request merged**
