### PR TITLE
Update Overview chapter in documentation to Charts 6

### PR DESCRIPTION
**Pull request by johannesh2**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/72)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/charts-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72#-L2Kwh7vqqLpFY8lSr9I:-L2Kwh7vqqLpFY8lSr9J:b7ut338) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/54de7ac6a6676f62873dfc440a4656b899a81138/documentation/charts-overview.asciidoc#L20)):*
> one-
Is this dash needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Comment by johannesh2** [comment]
*[documentation/charts-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72#-L2Kwh7vqqLpFY8lSr9I:-L2L3ToRdSr5YUpApfWP:b-drbl7h) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/54de7ac6a6676f62873dfc440a4656b899a81138/documentation/charts-overview.asciidoc#L20)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

> one-
Is this dash needed?
</blockquote></details>

I guess it can be there, but then two dimensional should be written two-dimensional.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/charts-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72#-L2Kwh7vqqLpFY8lSr9I:-L2L3q_MreNlg15q9FwJ:b3wazgz) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/54de7ac6a6676f62873dfc440a4656b899a81138/documentation/charts-overview.asciidoc#L20)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

I guess it can be there, but then two dimensional should be written two-dimensional.
</blockquote></details>

As in line 12.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/charts-overview.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72#-L2Kwh7vqqLpFY8lSr9I:-L2L4BcVwRk8_MsKRaJ8:b-5oa6sl) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/54de7ac6a6676f62873dfc440a4656b899a81138/documentation/charts-overview.asciidoc#L20)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

As in line 12.
</blockquote></details>

TBH it's not the best literature anyways. I'll think about how to rephrase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/charts-overview.asciidoc, line 11 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72#-L2LAsWSUb-mL33vCED5:-L2LAsWSUb-mL33vCED6:b-8bl8s3) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/fdb5f942dc100b1bb07aff3a2420eea0fdcc1588/documentation/charts-overview.asciidoc#L11)):*
> one- or two dimensional

I guess this was left unnoticed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/72)*

**Pull request merged**
