### PR TITLE
Properly capitalize category captions

### PR DESCRIPTION
**Pull request by sayo-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts-flow/26)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/src/main/java/com/vaadin/addon/charts/Category.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26#-Kz3Y8oitEvHltLguReG:-Kz3Y8oitEvHltLguReH:bbqvz8z) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/6943fb3e1ec14c1cfb6cbb2fe4b9d5bef883b0c8/demo/src/main/java/com/vaadin/addon/charts/Category.java#L50)):*
> ```Java
>                 .replace("bar", "Bar")
>                 .replace("scatter", "Scatter")
>                 .replace("provider", "Provider");
> ```

Is there any demo with "provider" on their package name? I've made a quick search on our current demo list, and couldn't find any.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26)*

**Comment by sayo-vaadin** [comment]
*[demo/src/main/java/com/vaadin/addon/charts/Category.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26#-Kz3Y8oitEvHltLguReG:-Kz3ZMyVcgm0HnGRpME-:bmmmwqt) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/6943fb3e1ec14c1cfb6cbb2fe4b9d5bef883b0c8/demo/src/main/java/com/vaadin/addon/charts/Category.java#L50)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Is there any demo with "provider" on their package name? I've made a quick search on our current demo list, and couldn't find any.
</blockquote></details>

That was added because of https://github.com/vaadin/charts/blob/master/demo/src/main/java/com/vaadin/addon/charts/ChartsDemoUI.java#L87
I felt there was one in the past, or might be one in future but on a second thought, I'll remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26)*

**Comment by sayo-vaadin** [comment]
*[demo/src/main/java/com/vaadin/addon/charts/Category.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26#-Kz3Y8oitEvHltLguReG:-Kz3_w0VVRLk-AAZ8LWy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts-flow/blob/6943fb3e1ec14c1cfb6cbb2fe4b9d5bef883b0c8/demo/src/main/java/com/vaadin/addon/charts/Category.java#L50)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

That was added because of https://github.com/vaadin/charts/blob/master/demo/src/main/java/com/vaadin/addon/charts/ChartsDemoUI.java#L87
I felt there was one in the past, or might be one in future but on a second thought, I'll remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts-flow/26#-:-Kz3adF57wkQi6sExTgu:bnfp4nl)*

**Pull request merged**
